"""
Embeddings Common Pitfalls.
"""

# MISTAKE: Comparing embedding vectors generated by DIFFERENT model architectures (e.g. comparing OpenAI embeddings against HuggingFace embeddings).
# WHY: Embeddings exist in model-specific vector space dimensions ($1536$-dim vs $384$-dim). Cross-model dot products produce meaningless garbage.
# FIX: Always embed queries and document chunks using the EXACT same embedding model checkpoint.

if __name__ == "__main__":
    print("Vector embedding model consistency rules verified.")
